package projectx

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Path}

// 生成 outer_product_tile_bits 对应的 HLS 配套文件：
// - outer_product_tile.hpp: kernel 直接 include 的 C 声明/宏封装
// - outer_product_tile_model.cpp: 非综合路径的软件模型
// - outer_product_tile.json: Vitis HLS black-box 绑定信息
// - create_outer_product_tile_dmul_ip.tcl: Vivado FP64 multiply IP 生成脚本
//
// 这里不仅生成“文件”，也集中维护 tile black-box 的接口文档，避免：
// - HLS 调用点以为它是数组接口
// - JSON 以为它是标量接口
// - Chisel wrapper / header / 调用点三边对同一个端口顺序理解不一致
object OuterProductTileFiles {
  private val tileSize = 8
  private val outputCount = tileSize * tileSize
  private val lhsNames = Seq.tabulate(tileSize)(i => s"lhs${i}_bits")
  private val rhsNames = Seq.tabulate(tileSize)(i => s"rhs${i}_bits")
  private val outputNames = Seq.tabulate(outputCount)(i => s"out${i}_bits")
  private val inputNames = lhsNames ++ rhsNames

  def write(targetDir: String): Unit = {
    val dir = Path.of(targetDir).toAbsolutePath.normalize()
    Files.createDirectories(dir)
    writeFile(dir.resolve("outer_product_tile.hpp"), header)
    writeFile(dir.resolve("outer_product_tile_model.cpp"), model)
    writeFile(dir.resolve("outer_product_tile.json"), json(dir))
    writeFile(dir.resolve("create_outer_product_tile_dmul_ip.tcl"), ipTcl(dir))
  }

  private def writeFile(path: Path, text: String): Unit =
    Files.write(path, text.getBytes(StandardCharsets.UTF_8))

  private def renderMacro(name: String, lines: Seq[String]): String = {
    val prefix = s"#define $name "
    if (lines.isEmpty) {
      prefix
    } else {
      val body = lines.zipWithIndex.map { case (line, index) =>
        val suffix = if (index == lines.length - 1) "" else " \\"
        s"    $line$suffix"
      }
      (prefix + "\\") + "\n" + body.mkString("\n")
    }
  }

  private def declarationArgs: Seq[String] =
    inputNames.map(name => s"unsigned long long $name") ++
      outputNames.map(name => s"unsigned long long& $name")

  private def functionDeclaration(name: String): String =
    declarationArgs.mkString(s"void $name(", ",\n                            ", ");")

  private val wrapperCall: String = {
    val args =
      (0 until tileSize).map(i => s"(lhs_bits)[$i]") ++
        (0 until tileSize).map(i => s"(rhs_bits)[$i]") ++
        outputNames.map(name => s"prefix##_$name")
    args.mkString("outer_product_tile_bits(", ",\n                            ", ");")
  }

  private val header: String = {
    val inputMacro = renderMacro("PROJECTX_OUTER_PRODUCT_TILE_INPUT_PARAMS", inputNames.map(name => s"unsigned long long $name,").updated(inputNames.length - 1, s"unsigned long long ${inputNames.last}"))
    val outputMacro = renderMacro("PROJECTX_OUTER_PRODUCT_TILE_OUTPUT_PARAMS", outputNames.map(name => s"unsigned long long& $name,").updated(outputNames.length - 1, s"unsigned long long& ${outputNames.last}"))
    val outputPtrMacro = renderMacro("PROJECTX_OUTER_PRODUCT_TILE_OUTPUT_PTRS", outputNames.map(name => s"&$name,").updated(outputNames.length - 1, s"&${outputNames.last}"))
    val declareOutputVars = renderMacro(
      "PROJECTX_OUTER_PRODUCT_TILE_DECLARE_OUTPUTS(prefix)",
      outputNames.map(name => s"unsigned long long prefix##_$name = 0;")
    )
    val copyOutputVars = renderMacro(
      "PROJECTX_OUTER_PRODUCT_TILE_COPY_OUTPUTS(prefix, out_bits)",
      outputNames.zipWithIndex.map { case (name, index) =>
        s"(out_bits)[$index] = prefix##_$name;"
      }
    )
    val callMacro = renderMacro(
      "PROJECTX_OUTER_PRODUCT_TILE_CALL(lhs_bits, rhs_bits, prefix)",
      wrapperCall.split('\n').toSeq
    )
    val lhsValues = lhsNames.map(name => s"        projectx_tile_bits_to_double($name)").mkString(",\n")
    val rhsValues = rhsNames.map(name => s"        projectx_tile_bits_to_double($name)").mkString(",\n")

    s"""#ifndef PROJECTX_OUTER_PRODUCT_TILE_HPP
      |#define PROJECTX_OUTER_PRODUCT_TILE_HPP
      |
      |// Generated by OuterProductTileFiles.scala.
      |//
      |// 当前调用点：
      |// - hardware/chisel_core/krnl_spmv.cpp
      |// - hardware/hybrid/krnl_spmv.cpp
      |//
      |// 这两个 kernel 会先准备：
      |// - lhs_tile[8]：tile 的 8 个行元素
      |// - rhs_tile[8]：tile 的 8 个列元素
      |// - out_tile[64]：row-major 展平后的输出 tile
      |//
      |// 然后依次使用：
      |// 1. PROJECTX_OUTER_PRODUCT_TILE_DECLARE_OUTPUTS(tile_out)
      |// 2. PROJECTX_OUTER_PRODUCT_TILE_CALL(lhs_tile, rhs_tile, tile_out)
      |// 3. PROJECTX_OUTER_PRODUCT_TILE_COPY_OUTPUTS(tile_out, out_tile)
      |//
      |// HLS black-box JSON 只能把“一个 C 参数”映射到“一个 RTL 端口”，
      |// 所以实际导出的函数原型是标量展开形式，而不是数组形式。
      |//
      |// 参数含义：
      |// - lhs0_bits .. lhs7_bits: lhs_tile[0..7]，决定输出的 row 维
      |// - rhs0_bits .. rhs7_bits: rhs_tile[0..7]，决定输出的 col 维
      |// - out(row * 8 + col)_bits: row-major 输出，值等于 lhs[row] * rhs[col]
      |// 所有参数都用 unsigned long long 承载 IEEE-754 double 的原始 bit pattern。
      |//
      |// 真正硬件实现不是这个头文件里的 inline model，而是：
      |// HLS C 调用 -> outer_product_tile.json -> outer_product_tile_bits.v ->
      |// outer_product_tile_dmul_ip -> Xilinx floating_point IP。
      |//
      |// 以下三个宏的分工：
      |// - INPUT/OUTPUT_PARAMS: 生成函数声明所需的 16 入 + 64 出标量参数列表
      |// - OUTPUT_PTRS: 在软件模型里把 64 个引用参数组装成指针数组
      |// - DECLARE/CALL/COPY: 给 HLS kernel 提供“数组风格”的调用体验
      |//
      |$inputMacro
      |
      |$outputMacro
      |
      |$outputPtrMacro
      |
      |$declareOutputVars
      |
      |$callMacro
      |
      |$copyOutputVars
      |
      |${functionDeclaration("outer_product_tile_bits")}
      |
      |#ifndef PROJECTX_OUTER_PRODUCT_TILE_NO_INLINE_MODEL
      |// 非综合路径下，头文件直接提供一个软件等价模型，避免缺失符号。
      |// 综合时 outer_product_tile.json 会把同名函数绑定到 RTL black-box。
      |inline unsigned long long projectx_tile_double_to_bits(double value) {
      |    union {
      |        double d;
      |        unsigned long long u;
      |    } convert;
      |    convert.d = value;
      |    return convert.u;
      |}
      |
      |inline double projectx_tile_bits_to_double(unsigned long long value) {
      |    union {
      |        double d;
      |        unsigned long long u;
      |    } convert;
      |    convert.u = value;
      |    return convert.d;
      |}
      |
      |inline void outer_product_tile_bits(
      |    PROJECTX_OUTER_PRODUCT_TILE_INPUT_PARAMS,
      |    PROJECTX_OUTER_PRODUCT_TILE_OUTPUT_PARAMS) {
      |    // 软件模型按与 RTL 完全相同的 row-major 下标规则计算外积。
      |    const double lhs[$tileSize] = {
      |$lhsValues
      |    };
      |    const double rhs[$tileSize] = {
      |$rhsValues
      |    };
      |    unsigned long long* out_ptrs[$outputCount] = {
      |        PROJECTX_OUTER_PRODUCT_TILE_OUTPUT_PTRS
      |    };
      |
      |    for (int row = 0; row < $tileSize; ++row) {
      |        for (int col = 0; col < $tileSize; ++col) {
      |            *out_ptrs[row * $tileSize + col] =
      |                projectx_tile_double_to_bits(lhs[row] * rhs[col]);
      |        }
      |    }
      |}
      |#endif
      |
      |#endif
      |""".stripMargin
  }

  private val model: String =
    s"""#define PROJECTX_OUTER_PRODUCT_TILE_NO_INLINE_MODEL
      |#include "outer_product_tile.hpp"
      |
      |namespace {
      |
      |unsigned long long tile_double_to_bits(double value) {
      |    union {
      |        double d;
      |        unsigned long long u;
      |    } convert;
      |    convert.d = value;
      |    return convert.u;
      |}
      |
      |double tile_bits_to_double(unsigned long long value) {
      |    union {
      |        double d;
      |        unsigned long long u;
      |    } convert;
      |    convert.u = value;
      |    return convert.d;
      |}
      |
      |} // namespace
      |
      |void outer_product_tile_bits(
      |    PROJECTX_OUTER_PRODUCT_TILE_INPUT_PARAMS,
      |    PROJECTX_OUTER_PRODUCT_TILE_OUTPUT_PARAMS) {
      |    // 单独的 .cpp model 供 HLS C 仿真 / sw_emu 使用，行为与头文件 inline model 相同。
      |    const double lhs[$tileSize] = {
      |${lhsNames.map(name => s"        tile_bits_to_double($name)").mkString(",\n")}
      |    };
      |    const double rhs[$tileSize] = {
      |${rhsNames.map(name => s"        tile_bits_to_double($name)").mkString(",\n")}
      |    };
      |    unsigned long long* out_ptrs[$outputCount] = {
      |        PROJECTX_OUTER_PRODUCT_TILE_OUTPUT_PTRS
      |    };
      |
      |    for (int row = 0; row < $tileSize; ++row) {
      |        for (int col = 0; col < $tileSize; ++col) {
      |            *out_ptrs[row * $tileSize + col] =
      |                tile_double_to_bits(lhs[row] * rhs[col]);
      |        }
      |    }
      |}
      |""".stripMargin

  private def inputParam(name: String): String =
    s"""    {
      |      "c_name": ${jsonString(name)},
      |      "c_port_direction": "in",
      |      "rtl_ports": {
      |        "data_read_in": ${jsonString(name)}
      |      }
      |    }""".stripMargin

  private def outputParam(name: String): String =
    s"""    {
      |      "c_name": ${jsonString(name)},
      |      "c_port_direction": "out",
      |      "rtl_ports": {
      |        "data_write_out": ${jsonString(name)},
      |        "data_write_valid": ${jsonString(name + "_ap_vld")}
      |      }
      |    }""".stripMargin

  private def json(dir: Path): String = {
    val modelFile = jsonString(dir.resolve("outer_product_tile_model.cpp").toString)
    val wrapperFile = jsonString(dir.resolve("outer_product_tile_bits.v").toString)
    val ipWrapperFile = jsonString(dir.resolve("ip/outer_product_tile_dmul_ip/synth/outer_product_tile_dmul_ip.v").toString)
    val ipRfsFile = jsonString(dir.resolve("ip/outer_product_tile_dmul_ip/hdl/floating_point_v7_1_rfs.v").toString)
    val parameters = (inputNames.map(inputParam) ++ outputNames.map(outputParam)).mkString(",\n")

    s"""{
      |  "c_function_name": "outer_product_tile_bits",
      |  "rtl_top_module_name": "outer_product_tile_bits",
      |  "c_files": [
      |    {
      |      "c_file": $modelFile,
      |      "cflag": ${jsonString("-I" + dir.toString)}
      |    }
      |  ],
      |  "rtl_files": [
      |    $wrapperFile,
      |    $ipWrapperFile,
      |    $ipRfsFile
      |  ],
      |  "c_parameters": [
      |$parameters
      |  ],
      |  "rtl_common_signal": {
      |    "module_clock": "ap_clk",
      |    "module_reset": "ap_rst",
      |    "module_clock_enable": "ap_ce",
      |    "ap_ctrl_chain_protocol_idle": "ap_idle",
      |    "ap_ctrl_chain_protocol_start": "ap_start",
      |    "ap_ctrl_chain_protocol_ready": "ap_ready",
      |    "ap_ctrl_chain_protocol_done": "ap_done",
      |    "ap_ctrl_chain_protocol_continue": "ap_continue"
      |  },
      |  "rtl_performance": {
      |    "latency": "6",
      |    "II": "1"
      |  },
      |  "rtl_resource_usage": {
      |    "FF": "0",
      |    "LUT": "0",
      |    "BRAM": "0",
      |    "URAM": "0",
      |    "DSP": "704"
      |  }
      |}
      |""".stripMargin
  }

  private def ipTcl(dir: Path): String = {
    val ipDir = dir.resolve("ip").toString
    s"""set ip_dir [file normalize ${tclString(ipDir)}]
      |file mkdir $$ip_dir
      |create_project -in_memory -part xcu55c-fsvh2892-2L-e
      |
      |set vivado_ver [version -short]
      |set fpo_ver 7.1
      |if {[regexp -nocase {2015\\.1.*} $$vivado_ver match]} {
      |    set fpo_ver 7.0
      |}
      |
      |create_ip -name floating_point -version $$fpo_ver -vendor xilinx.com -library ip -module_name outer_product_tile_dmul_ip -dir $$ip_dir -force
      |set_property -dict [list CONFIG.a_precision_type Double \\
      |                          CONFIG.a_tuser_width 1 \\
      |                          CONFIG.add_sub_value Both \\
      |                          CONFIG.b_tuser_width 1 \\
      |                          CONFIG.c_a_exponent_width 11 \\
      |                          CONFIG.c_a_fraction_width 53 \\
      |                          CONFIG.c_compare_operation Programmable \\
      |                          CONFIG.c_has_divide_by_zero false \\
      |                          CONFIG.c_has_invalid_op false \\
      |                          CONFIG.c_has_overflow false \\
      |                          CONFIG.c_has_underflow false \\
      |                          CONFIG.c_latency 6 \\
      |                          CONFIG.c_mult_usage Max_Usage \\
      |                          CONFIG.c_optimization Speed_Optimized \\
      |                          CONFIG.c_rate 1 \\
      |                          CONFIG.c_result_exponent_width 11 \\
      |                          CONFIG.c_result_fraction_width 53 \\
      |                          CONFIG.component_name outer_product_tile_dmul_ip \\
      |                          CONFIG.flow_control NonBlocking \\
      |                          CONFIG.has_a_tlast false \\
      |                          CONFIG.has_a_tuser false \\
      |                          CONFIG.has_aclken true \\
      |                          CONFIG.has_aresetn false \\
      |                          CONFIG.has_b_tlast false \\
      |                          CONFIG.has_b_tuser false \\
      |                          CONFIG.has_operation_tlast false \\
      |                          CONFIG.has_operation_tuser false \\
      |                          CONFIG.has_result_tready false \\
      |                          CONFIG.maximum_latency false \\
      |                          CONFIG.operation_tuser_width 1 \\
      |                          CONFIG.operation_type Multiply \\
      |                          CONFIG.result_precision_type Double \\
      |                          CONFIG.result_tlast_behv Null] [get_ips outer_product_tile_dmul_ip] -quiet
      |set_property generate_synth_checkpoint false [get_files outer_product_tile_dmul_ip.xci]
      |generate_target {synthesis simulation} [get_files outer_product_tile_dmul_ip.xci]
      |close_project
      |""".stripMargin
  }

  private def jsonString(value: String): String =
    "\"" + value.flatMap {
      case '\\' => "\\\\"
      case '"' => "\\\""
      case c => c.toString
    } + "\""

  private def tclString(value: String): String =
    "{" + value + "}"
}
